#!/bin/bash

# TODO:
# - Images (with compression that can be skipped if image exists already)
# - Avoid file name collisions?
# - Internal wikilinks (mostly done)
# - Use updated_at timestamp? (done) Can this data be lost if files are moved/copied?
# - Do I want nate.spot/my-note or nate.spot/notes/my-note? (the former)

# -e → exit on error
# -u → error on unset variables
# -o pipefail → fail if any part of a pipeline fails
set -euo pipefail

# convert to lowercase
# remove apostrophes
# replace non-alphanumerics with hyphens
# trim leading/trailing hyphens
function slugify() {
    echo "$1" |
    tr '[:upper:]' '[:lower:]' |
    sed -E "s/['’]//g; s/[^a-z0-9]+/-/g; s/^-+|-+$//g"
}

function dash_to_space() {
    echo "$1" | sed -E "s/[-]/ /g"
}

function capitalize() {
    echo "${1^}"
}

notes_dir="$HOME/Documents/Notes/Natespot"
proj_dir="$HOME/Projects/nate-spot-v2"
site_dir="$proj_dir/site"

temp_dir="$proj_dir/temp"
notes_html_dir="$site_dir/notes"
tags_dir="$site_dir/tags"
tags_dir_temp="$temp_dir/tags"
# exclude_dir="private"

# Reset site directory
rm -rf "$site_dir"
rm -rf "$temp_dir"

mkdir -p "$notes_html_dir" # Make /site and /site/notes
mkdir -p "$tags_dir" # Make /site/tags
mkdir -p "$tags_dir_temp" # make /temp and /temp/tags

# Copy images, fonts, styles over to /site
cp -r "$notes_dir/images" "$site_dir"
cp -r "$proj_dir/fonts" "$site_dir"
cp -r "$proj_dir/styles" "$site_dir"

# Set up home, notes, tags, and temp page file paths
home_page_name="_Home"
home_page_md="$notes_dir/$home_page_name.md"

home_page_md_temp="$temp_dir/$home_page_name.md"
notes_index_md_temp="$temp_dir/Notes.md"
tags_index_md_temp="$temp_dir/Tags.md"

notes_index_description="All my thoughts and jots, with the most recently updated on top.\n\n"
tags_index_description="Some of the topics I've scribbled about.\n\n"
tag_page_description="My ramblings on this topic. See [all tags](/tags/index.html) for more.\n\n"

# Use printf instead of echo so newlines (\n) are handled properly
touch $notes_index_md_temp
printf "$notes_index_description" >> $notes_index_md_temp

touch $tags_index_md_temp
printf "$tags_index_description" >> $tags_index_md_temp

home_page_html="$site_dir/index.html"
notes_index_html="$notes_html_dir/index.html"
tags_index_html="$tags_dir/index.html"

# Begin processing

# For each markdown file:
# 1. Create its html page
# 2. Extract its tags (if any)
# 3. Create a markdown page for each tag (if it doesn't exist)
# 4. Add a link to the post in the tag page
#
# For reference, how to exclude a dir:
# -type d -name "$exclude_dir" -prune -o \
#
find "$notes_dir" \
    -type f ! -name "*.sync-conflict*" -name "*.md" -printf '%T@ %p\0' | \
    sort -z -nr | \
    while IFS= read -r -d '' entry; do
        file="${entry#* }"
        title=$(basename "$file" .md)
        slug=$(slugify "$title")
        page_dir="$site_dir/$slug"
        updated_at=$(date -r "$file" +%Y-%m-%d)

        # Don't make the home page into a note
        if [[ "$title" == $home_page_name ]]; then
            continue
        fi

        echo "Making page: $slug"

        mkdir -p "$page_dir" # Assumes directory does not exist. Duplicate file names are possible...
        tags=$(
            pandoc "$file" -o "$page_dir/index.html" \
                --metadata title="$title" \
                --metadata updated_at="$updated_at" \
                --lua-filter=pandoc/meta.lua \
                --template pandoc/template.html \
                --include-before-body pandoc/header.html \
                --include-after-body pandoc/footer.html
        )

        # Add link to note in notes index markdown file
        echo "- [$title](/$slug)" >> $notes_index_md_temp

        # Make tags pages
        IFS=',' read -a tag_array <<< "$tags"

        for tag in "${tag_array[@]}"; do
            tag_page_md_temp="$tags_dir_temp/$tag.md"

            if [[ ! -f "$tag_page_md_temp" ]]; then
                touch "$tag_page_md_temp"
                printf "$tag_page_description" >> $tag_page_md_temp
            fi

            echo "- [$title](/$slug)" >> $tag_page_md_temp
        done
done

# For each tag markdown file:
# 1. Create its html page
# 2. Add a link to the tag in the tag index markdown file

for tag_md in "$tags_dir_temp"/*.md; do
    # [ -e "$tag_md" ] || continue  # handle no matches
    tag_title=$(basename "$tag_md" .md)
    tag_dir="$tags_dir/$tag_title"

    echo "Making tag: $tag_title"

    # Make /site/tags/$tag_title
    mkdir $tag_dir

    tag_page="$tag_dir/index.html"
    tag_title_formatted=$(capitalize "$(dash_to_space $tag_title)")

    pandoc "$tag_md" -o "$tag_page" \
        --metadata title="$tag_title_formatted" \
        --template pandoc/template.html \
        --include-before-body pandoc/header.html \
        --include-after-body pandoc/footer.html

    echo "- [$tag_title_formatted](/tags/$tag_title)" >> $tags_index_md_temp

    # rm $tag_md
done

# Make home page
echo "Making home page"

pandoc "$home_page_md" -o "$home_page_html" \
    --template pandoc/template.html \
    --lua-filter=pandoc/meta.lua \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# Make notes index page
echo "Making notes page"

notes_index_title=$(basename "$notes_index_md_temp" .md)

pandoc "$notes_index_md_temp" -o "$notes_index_html" \
    --metadata title="$notes_index_title" \
    --template pandoc/template.html \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# Make tags index page
echo "Making tags page"

tags_index_title=$(basename "$tags_index_md_temp" .md)

pandoc "$tags_index_md_temp" -o "$tags_index_html" \
    --metadata title="$tags_index_title" \
    --template pandoc/template.html \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# Remove temp directory
echo "Removing temp directory"
rm -rf "$temp_dir"


# tags=$(pandoc "md/My First Post.md" -o html/post.html --lua-filter=pandoc/meta.lua --template pandoc/template.html)
# title=$(jq -r '.title' <<<"$json")
# echo "$tags"

# readarray -t meta_array < <(pandoc md/post.md --lua-filter=pandoc/meta.lua)
# printf '%s\n' "${meta_array[0]}"

# IFS=',' read -a meta_list <<< "$meta_string"

# for i in "${meta_list[@]}"; do
#     echo $i
# done
#
# <!--
