#!/bin/bash

# TODO:
# - Images (with compression that can be skipped if image exists already)
# - Avoid file name collisions?
# - Internal wikilinks (mostly done)
# - Use updated_at timestamp? Can this data be lost if files are moved/copied?
# - Do I want nate.spot/my-note or nate.spot/notes/my-note?

# -e → exit on error
# -u → error on unset variables
# -o pipefail → fail if any part of a pipeline fails
set -euo pipefail

# remove apostrophes
# replace non-alphanumerics with hyphens
# trim leading/trailing hyphens
function slugify() {
    echo "$1" |
    tr '[:upper:]' '[:lower:]' |
    sed -E "s/['’]//g; s/[^a-z0-9]+/-/g; s/^-+|-+$//g"
}

notes_dir="$HOME/Documents/Notes/Natespot"
proj_dir="$HOME/Projects/nate-spot-v2"
site_dir="$proj_dir/site"

images_dir_source="$notes_dir/images"
fonts_dir_source="$proj_dir/fonts"
# images_dir_dest="$site_dir/images"

temp_dir="$proj_dir/temp"
notes_html_dir="$site_dir/notes"
tags_dir="$site_dir/tags"
tags_dir_temp="$temp_dir/tags"
# exclude_dir="private"

# Reset site directory
rm -rf "$site_dir"
rm -rf "$temp_dir"

mkdir -p "$notes_html_dir" # Make /site and /site/notes
mkdir -p "$tags_dir" # Make /site/tags
mkdir -p "$tags_dir_temp" # make /temp and /temp/tags
# mkdir -p "$images_dir_dest" # Make /site/images

# Copy images and styles over to /site
cp -r "$images_dir_source" "$site_dir"
cp -r "$fonts_dir_source" "$site_dir"
cp "$proj_dir/styles.css" "$site_dir/styles.css"
# cp "$proj_dir/fonts/libre-baskerville.woff2" "$site_dir/fonts/libre-baskerville.woff2"
# cp "$proj_dir/fonts/ibm-plex-sans.woff2" "$site_dir/fonts/ibm-plex-sans.woff2"

# Set up home, notes, tags, and temp page file paths
home_page_name="_Home"
notes_page_name="_Notes"
tags_page_name="_Tags"

home_page_md="$notes_dir/$home_page_name.md"
notes_page_md="$notes_dir/$notes_page_name.md"
tags_page_md="$notes_dir/$tags_page_name.md"

home_page_md_temp="$temp_dir/$home_page_name.md"
notes_page_md_temp="$temp_dir/$notes_page_name.md"
tags_page_md_temp="$temp_dir/$tags_page_name.md"

cp $notes_page_md $notes_page_md_temp
cp $tags_page_md $tags_page_md_temp

home_page_html="$site_dir/index.html"
notes_page_html="$notes_html_dir/index.html"
tags_page_html="$tags_dir/index.html"

# Begin processing

# For each markdown file:
# 1. Create its html page
# 2. Extract its tags (if any)
# 3. Create a markdown page for each tag (if it doesn't exist)
# 4. Add a link to the post in the tag page
#
# For reference, how to exclude a dir:
# -type d -name "$exclude_dir" -prune -o \
#
find "$notes_dir" \
    -type f -name "*.md" -print0 | \
    while IFS= read -r -d '' file; do
        title=$(basename "$file" .md)
        slug=$(slugify "$title")
        page_dir="$site_dir/$slug"
        updated_at=$(date -r "$file" +%Y-%m-%d)

        # Don't make the home, notes, or tags pages into notes
        if [[ "$title" == $home_page_name ]] ||
            [[ "$title" == $notes_page_name ]] ||
            [[ "$title" == $tags_page_name ]]; then
            continue
        fi

        echo "Making page: $slug"

        mkdir -p "$page_dir" # Assumes directory does not exist. Duplicate file names are possible...
        tags=$(
            pandoc "$file" -o "$page_dir/index.html" \
                --metadata title="$title" \
                --metadata updated_at="$updated_at" \
                --lua-filter=pandoc/meta.lua \
                --template pandoc/template.html \
                --include-before-body pandoc/header.html \
                --include-after-body pandoc/footer.html
        )

        # Add link to note in notes index markdown file
        echo "- [$title](/$slug)" >> $notes_page_md_temp

        # Make tags pages
        IFS=',' read -a tag_array <<< "$tags"

        for tag in "${tag_array[@]}"; do
            tag_page="$tags_dir_temp/$tag.md"

            if [[ ! -f "$tag_page" ]]; then
                # Creates /site/$tag.md. To be deleted after pandoc conversion.
                touch "$tag_page"
            fi

            echo "- [$title](/$slug)" >> $tag_page
        done
done

# For each tag markdown file:
# 1. Create its html page
# 2. Add a link to the tag in the tag index markdown file

for tag_md in "$tags_dir_temp"/*.md; do
    # [ -e "$tag_md" ] || continue  # handle no matches
    tag_title=$(basename "$tag_md" .md)
    tag_dir="$tags_dir/$tag_title"

    echo "Making tag: $tag_title"

    # Make /site/tags/$tag_title
    mkdir $tag_dir

    tag_page="$tag_dir/index.html"

    pandoc "$tag_md" -o "$tag_page" \
        --metadata title="Notes on $tag_title" \
        --template pandoc/template.html \
        --include-before-body pandoc/header.html \
        --include-after-body pandoc/footer.html

    echo "- [$tag_title](/tags/$tag_title)" >> $tags_page_md_temp

    rm $tag_md
done

# Make home page
echo "Making home page"
# site_index_md="$notes_dir/$home_page_filename.md"

pandoc "$home_page_md" -o "$home_page_html" \
    --template pandoc/template.html \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# Make notes index page
echo "Making notes page"

# notes_index_folder="$site_dir/notes"
# mkdir $notes_index_folder

# notes_index_html="$notes_index_folder/index.html"

pandoc "$notes_page_md_temp" -o "$notes_page_html" \
    --metadata title="Notes" \
    --template pandoc/template.html \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# rm $notes_index_md

# Make tags index page
echo "Making tags page"

pandoc "$tags_page_md_temp" -o "$tags_page_html" \
    --metadata title="Tags" \
    --template pandoc/template.html \
    --include-before-body pandoc/header.html \
    --include-after-body pandoc/footer.html

# Remove temp directory
echo "Removing temp directory"
rm -rf "$temp_dir"


# tags=$(pandoc "md/My First Post.md" -o html/post.html --lua-filter=pandoc/meta.lua --template pandoc/template.html)
# title=$(jq -r '.title' <<<"$json")
# echo "$tags"

# readarray -t meta_array < <(pandoc md/post.md --lua-filter=pandoc/meta.lua)
# printf '%s\n' "${meta_array[0]}"

# IFS=',' read -a meta_list <<< "$meta_string"

# for i in "${meta_list[@]}"; do
#     echo $i
# done
#
# <!--
